# 项目配置
project:
  name: Latte Admin
  app-name: latte-admin
  version: 1.0.0
  description: 持续迭代优化的前后端分离中后台管理系统框架。
  base-package: com.ppxb.latte.admin
  contact:
    name: ppxb

# Spring 配置
spring:
  application:
    name: ${project.app-name}
  profiles:
    active: dev

# 服务器配置
server:
  servlet:
    context-path: /
  undertow:
    max-http-post-size: -1
    buffer-size: 512
    direct-buffers: true
    threads:
      io: 8
      worker: 256

# 接口文档配置
springdoc:
  default-flat-param-object: true
# 接口文档增强配置
knife4j:
  enable: true
  setting:
    enable-footer: false
    enable-footer-custom: true
    footer-custom-content: 'Copyright © 2024 ${project.contact.name}&nbsp;⋅&nbsp;${project.name} v${project.version}'

# 日志配置
latte-starter.log:
  includes:
    - DESCRIPTION
    - MODULE
    - REQUEST_HEADERS
    - REQUEST_BODY
    - IP_ADDRESS
    - BROWSER
    - OS
    - RESPONSE_HEADERS
    - RESPONSE_BODY
logging:
  config: classpath:logback-spring.xml

latte-starter:
  web:
    response:
      i18n: false
      default-http-status-code-on-error: 200
      default-success-code: 0
      default-success-msg: ok
      default-error-code: -1
      default-error-msg: error
      origin-exception-using-detail-message: false
