# 项目配置
project:
  name: Latte Admin
  app-name: latte-admin
  version: 1.0.0
  description: 持续迭代优化的前后端分离中后台管理系统框架。
  base-package: com.ppxb.latte.admin
  contact:
    name: ppxb
  license:
    name: MIT

# 日志配置
latte-starter.log:
  # 包含信息
  includes:
    - DESCRIPTION
    - MODULE
    - REQUEST_HEADERS
    - REQUEST_BODY
    - IP_ADDRESS
    - BROWSER
    - OS
    - RESPONSE_HEADERS
    - RESPONSE_BODY
# 项目日志配置
logging:
  config: classpath:logback-spring.xml

# Web 配置
latte-starter.web:
  # 链路跟踪配置
  trace:
    enabled: true
    trace-id-name: traceId
    # TLog 配置
    tlog:
      enable-invoke-time-print: false
      pattern: '[$spanId][$traceId]'
      mdc-enable: false
  # 全局响应配置
  response:
    # 是否开启国际化（默认：false）
    i18n: false
    # 自定义失败 HTTP 状态码（默认：200，建议业务和通信状态码区分）
    default-http-status-code-on-error: 200
    # 自定义成功响应码（默认：0）
    default-success-code: 0
    # 自定义成功提示（默认：ok）
    default-success-msg: ok
    # 自定义失败响应码（默认：1）
    default-error-code: -1
    # 自定义失败提示（默认：error）
    default-error-msg: error
    # 是否将原生异常错误信息填充到状态信息中
    origin-exception-using-detail-message: false

# 全局树结构配置（简单树，对应前端 UI）
latte-starter.crud:
  tree:
    id-key: key
    name-key: title
    weight-key: sort

# 接口文档配置
springdoc:
  # 设置对象型参数的展示形式（设为 true 表示将对象型参数平展开，即对象内的属性直接作为参数展示而不是嵌套在对象内，默认 false）
  # 如果不添加该全局配置，可以在需要如此处理的对象参数类上使用 @ParameterObject
  default-flat-param-object: true
# 接口文档增强配置
knife4j:
  enable: true
  setting:
    # 是否显示默认的 footer（默认 true，显示）
    enable-footer: false
    # 是否自定义 footer（默认 false，非自定义）
    enable-footer-custom: true
    # 自定义 footer 内容，支持 Markdown 语法
    footer-custom-content: 'Copyright © 2024 ${project.contact.name}&nbsp;⋅&nbsp;${project.name} v${project.version}'

# Sa-Token 配置
sa-token:
  # token 名称（同时也是 cookie 名称）
  token-name: Authorization
  # token 有效期（单位：秒，默认 30 天，-1 代表永不过期）
  timeout: 86400
  # token 最低活跃频率（单位：秒，默认 -1，代表不限制，永不冻结。如果 token 超过此时间没有访问系统就会被冻结）
  active-timeout: 1800
  # 是否打开自动续签（如果此值为 true，框架会在每次直接或间接调用 getLoginId() 时进行一次过期检查与续签操作）
  auto-renew: true
  # 是否允许同一账号多地同时登录（为 true 时允许一起登录，为 false 时新登录挤掉旧登录）
  is-concurrent: true
  # 在多人登录同一账号时，是否共用一个 token（为 true 时所有登录共用一个 token，为 false 时每次登录新建一个 token）
  is-share: false
  # 是否输出操作日志
  is-log: false
  jwt-secret-key: asdksadioqwmeomqosidmwkqe
  # 扩展配置
  extension:
    enabled: true
    enable-jwt: true
    # 持久层配置
    dao:
      type: redis

# Mybatis Plus 配置
mybatis-plus:
  # Mapper XML 文件目录配置
  mapper-locations: classpath*:/mapper/**/*Mapper.xml
  # 类型别名扫描包配置
  type-aliases-package: ${project.base-package}.**.model
  # Mybatis 配置
  configuration:
    # Mybatis 自动映射策略
    # NONE: 不启用; PARTIAL: 只对非嵌套; resultMap: 自动映射; FULL: 对所有 resultMap 自动映射
    auto-mapping-behavior: partial
  # 全局配置
  global-config:
    banner: true
    db-config:
      # 主键类型（默认 assign_id，表示自行赋值）
      # auto 代表使用数据库自增策略（需要在表中设置好自增约束）
      id-type: assign_id
      # 逻辑删除字段
      logic-delete-field: isDeleted
      # 逻辑删除全局值（默认 1，表示已删除）
      logic-delete-value: 1
      # 逻辑未删除全局值（默认 0，表示未删除）
      logic-not-delete-value: 0
  # 扩展配置
  extension:
    enabled: true
    # Mapper 接口扫描包配置
    mapper-package: ${project.base-package}.**.mapper
    # ID 生成器配置
    id-generator:
      type: cosid
    # 分页插件配置
    pagination:
      enabled: true
      db-type: mysql

# CosId 配置
cosid:
  namespace: ${spring.application.name}
  machine:
    enabled: true
    # 机器号分配器
    distributor:
      type: redis
    guarder:
      # 开启机器号守护
      enabled: true
  snowflake:
    enabled: true
    zone-id: Asia/Shanghai
    epoch: 1577203200000
    share:
      # 开启时钟回拨同步
      clock-sync: true
      friendly: true
    provider:
      safe-js:
        machine-bit: 7
        sequence-bit: 9

# 服务器配置
server:
  servlet:
    # 应用访问路径
    context-path: /
  # Undertow 服务器配置
  undertow:
    # HTTP POST 请求内容的大小上限（默认 -1，不限制）
    max-http-post-size: -1
    # 影响 buffer 的配置，这些 buffer 会用于服务器的 IO 操作，类似 Netty 池化
    # 每块 buffer 的空间大小（越小的空间被利用越充分，不要设置太大，以免影响其他应用，合适即可）
    buffer-size: 512
    # 是否分配的直接内存（NIO 直接分配的堆外内存）
    direct-buffers: true
    threads:
      # IO 线程数，主要执行非阻塞的任务，它们会负责多个连接（默认每个 CPU 一个线程）
      io: 8
      # 阻塞任务线程池，当执行类似 Servlet 请求阻塞操作时，Undertow 会从该线程池中取得线程（值设置取决于系统负载）
      worker: 256

# Spring 配置
spring:
  application:
    name: ${project.app-name}
  main:
    # 允许定义重名的 bean 对象覆盖原有的 bean
    allow-bean-definition-overriding: true
    # 允许循环依赖
    allow-circular-references: true
  # 环境配置
  profiles:
    active: dev
  # 线程池配置（默认启用扩展配置，如未指定 corePoolSize、maxPoolSize 则根据机器配置自动设置）
  task:
    # 异步任务
    execution:
      thread-name-prefix: task-pool
      # 任务拒绝策略（默认 ABORT，详情参考 latte-starter-core/threadpool）
      rejected-policy: caller_runs
      pool:
        keep-alive: 300s
      shutdown:
        # 是否等待任务执行完成再关闭线程池
        await-termination: true
        # 等待时间
        await-termination-period: 30s
    # 定时任务
    scheduling:
      thread-name-prefix: schedule-pool
      rejected-policy: caller_runs
      shutdown:
        # 是否等待任务执行完成再关闭线程池
        await-termination: true
        # 等待时间
        await-termination-period: 30s


